### PR TITLE
Add support for Redis providers

### PR DESCRIPTION
**Pull request by brainix**
Add support for Redis providers.  As promised, @singingwolfboy, recreated PR as well as tagged you!

### CODE REVIEW

**Comment by brainix** [comment]
@singingwolfboy - just pinging you again!  Does this PR look ok?  Is there anything that I should change?  Thanks!

**Comment by singingwolfboy** [comment]
Sorry for the delay. This looks great to me! Have you tested it anywhere? If not, would you mind doing a quick test on Heroku with at least one Redis provider and at least one Mongo provider?

Once you verify that it's been tested, I'll merge this and cut a new release. :)

**Comment by brainix** [comment]
@singingwolfboy - I've only tested it locally, but you bring up an excellent point.  Let me test it on a real Heroku app tomorrow, and I'll reply on this PR with the results.  Thanks!

**Comment by singingwolfboy** [comment]
@brainix: any update on this?

**Comment by singingwolfboy** [comment]
@brainix: ping :)

**Pull request closed without merging**
